### ISSUE TITLE
the 'option' does not work in Demo4

### ISSUE THREAD

**Issue by ysuchao** [wzpan/cmake-demo#1]
under cmake version 2.8.12.2 the 'option' in CMakeList.txt does not work in its current order, actually the 'option' should be declared before 'configure_file'?

**Comment by wzpan** [comment]
It works for me. The order here doesn't matters.

I guess you are using `ccmake .` for configuring? Have you pressed `c` after chaning the value, and fire `make -B` to perform a force make?

**Comment by ysuchao** [comment]
I think you're right. I did 'ccmake .' and pressed 'c' to configure and this works as the tutorial says, and the result is the same when I did 'cmake . -i' and pressed 4 'Enter' afterwards. The config.h is listed below:
`#define USE_MYMATH` 

The confiusion is that, when I did 'cmake .'(**whitout a '-i' here**), the result in config.h is different from previous and now it is listed here:
`/* #undef USE_MYMATH */`

As the option says
`option (USE_MYMATH
	   "Use provided math implementation" ON)`
I think the content of config.h should be the same with the first one, but not.

And, then I change the order of the 
`option (USE_MYMATH
	   "Use provided math implementation" ON)`
and the 
`configure_file (
  "${PROJECT_SOURCE_DIR}/config.h.in"
  "${PROJECT_BINARY_DIR}/config.h"
  )`
in CMakeList.txt, did 'cmake .' and got the config.h like this:
`#define USE_MYMATH`
(This is what I think it should be)

As a beginner of cmake, this is not so easy to understand that the 'option(...)' has a value 'ON' but no use by a default 'cmake .'. 

After all, thank you for the tutorial and reply.

**Comment by wzpan** [comment]
Note that each step of CMake is cached.  Once you run `cmake .`, you will get a folder named `CMakeFiles` as well as a file called `CMakeCache.txt`. Also in this demo you will get a `config.h` file.

The CMake cache mechanism works like this: checks the following steps sequentially . If each step was finished before, skip it. Otherwise, executes that from that on.

- Configuring
- Generating
- Build files

Therefore, if you run `cmake .` again, since all the above three part was successfully done before, all of them are skipped. 

To avoid skipping and force CMake to go through all the steps all over again, you have to delete all the cached files before running `cmake .`. Then it should generate a new config file that contains the expected value.

As the contrast, `ccmake .` will force cmake to run configuring again. And that's why you get a right result after then.

**Comment by ysuchao** [comment]
Actually I did delete all the generated cache files and config.h every time(by using _git clean -fd_ and _git status_ to check). I' pretty sure that there is no remaining file.

Maybe I will test on other machines later.
